<?php
// Generated from Font Awesome Free 7.3.1 metadata. [ style/name, label ]
return [
['solid/0','0'],
['solid/1','1'],
['solid/2','2'],
['solid/3','3'],
['solid/4','4'],
['solid/5','5'],
['solid/6','6'],
['solid/7','7'],
['solid/8','8'],
['solid/9','9'],
['brands/42-group','42 Group'],
['brands/500px','500px'],
['solid/a','A'],
['brands/a11y-project','A11y Project'],
['brands/accessible-icon','Accessible Icon'],
['brands/accusoft','Accusoft'],
['regular/address-book','Address Book'],
['solid/address-book','Address Book'],
['regular/address-card','Address Card'],
['solid/address-card','Address Card'],
['brands/adn','Adn'],
['brands/adversal','Adversal'],
['brands/affiliatetheme','Affiliatetheme'],
['brands/airbnb','Airbnb'],
['regular/alarm-clock','Alarm Clock'],
['solid/alarm-clock','Alarm Clock'],
['brands/algolia','Algolia'],
['solid/align-center','Align Center'],
['solid/align-justify','Align Justify'],
['solid/align-left','Align Left'],
['solid/align-right','Align Right'],
['brands/alipay','Alipay'],
['brands/amazon','Amazon'],
['brands/amazon-pay','Amazon Pay'],
['brands/amilia','Amilia'],
['solid/anchor','Anchor'],
['solid/anchor-circle-check','Anchor Circle Check'],
['solid/anchor-circle-exclamation','Anchor Circle Exclamation'],
['solid/anchor-circle-xmark','Anchor Circle Xmark'],
['solid/anchor-lock','Anchor Lock'],
['brands/android','Android'],
['brands/angellist','Angellist'],
['solid/angle-down','Angle Down'],
['solid/angle-left','Angle Left'],
['solid/angle-right','Angle Right'],
['solid/angle-up','Angle Up'],
['solid/angles-down','Angles Down'],
['solid/angles-left','Angles Left'],
['solid/angles-right','Angles Right'],
['solid/angles-up','Angles Up'],
['brands/angrycreative','Angrycreative'],
['brands/angular','Angular'],
['solid/ankh','Ankh'],
['brands/app-store','App Store'],
['brands/app-store-ios','App Store Ios'],
['brands/apper','Apper'],
['brands/apple','Apple'],
['brands/apple-pay','Apple Pay'],
['solid/apple-whole','Apple Whole'],
['solid/aquarius','Aquarius'],
['brands/arch-linux','Arch Linux'],
['solid/archway','Archway'],
['solid/aries','Aries'],
['solid/arrow-down','Arrow Down'],
['solid/arrow-down-1-9','Arrow Down 1 9'],
['solid/arrow-down-9-1','Arrow Down 9 1'],
['solid/arrow-down-a-z','Arrow Down A Z'],
['solid/arrow-down-long','Arrow Down Long'],
['solid/arrow-down-short-wide','Arrow Down Short Wide'],
['solid/arrow-down-up-across-line','Arrow Down Up Across Line'],
['solid/arrow-down-up-lock','Arrow Down Up Lock'],
['solid/arrow-down-wide-short','Arrow Down Wide Short'],
['solid/arrow-down-z-a','Arrow Down Z A'],
['solid/arrow-left','Arrow Left'],
['solid/arrow-left-long','Arrow Left Long'],
['solid/arrow-pointer','Arrow Pointer'],
['solid/arrow-right','Arrow Right'],
['solid/arrow-right-arrow-left','Arrow Right Arrow Left'],
['solid/arrow-right-from-bracket','Arrow Right From Bracket'],
['solid/arrow-right-long','Arrow Right Long'],
['solid/arrow-right-to-bracket','Arrow Right To Bracket'],
['solid/arrow-right-to-city','Arrow Right To City'],
['solid/arrow-rotate-left','Arrow Rotate Left'],
['solid/arrow-rotate-right','Arrow Rotate Right'],
['solid/arrow-trend-down','Arrow Trend Down'],
['solid/arrow-trend-up','Arrow Trend Up'],
['solid/arrow-turn-down','Arrow Turn Down'],
['solid/arrow-turn-up','Arrow Turn Up'],
['solid/arrow-up','Arrow Up'],
['solid/arrow-up-1-9','Arrow Up 1 9'],
['solid/arrow-up-9-1','Arrow Up 9 1'],
['solid/arrow-up-a-z','Arrow Up A Z'],
['solid/arrow-up-from-bracket','Arrow Up From Bracket'],
['solid/arrow-up-from-ground-water','Arrow Up From Ground Water'],
['solid/arrow-up-from-water-pump','Arrow Up From Water Pump'],
['solid/arrow-up-long','Arrow Up Long'],
['solid/arrow-up-right-dots','Arrow Up Right Dots'],
['solid/arrow-up-right-from-square','Arrow Up Right From Square'],
['solid/arrow-up-short-wide','Arrow Up Short Wide'],
['solid/arrow-up-wide-short','Arrow Up Wide Short'],
['solid/arrow-up-z-a','Arrow Up Z A'],
['solid/arrows-down-to-line','Arrows Down To Line'],
['solid/arrows-down-to-people','Arrows Down To People'],
['solid/arrows-left-right','Arrows Left Right'],
['solid/arrows-left-right-to-line','Arrows Left Right To Line'],
['solid/arrows-rotate','Arrows Rotate'],
['solid/arrows-spin','Arrows Spin'],
['solid/arrows-split-up-and-left','Arrows Split Up And Left'],
['solid/arrows-to-circle','Arrows To Circle'],
['solid/arrows-to-dot','Arrows To Dot'],
['solid/arrows-to-eye','Arrows To Eye'],
['solid/arrows-turn-right','Arrows Turn Right'],
['solid/arrows-turn-to-dots','Arrows Turn To Dots'],
['solid/arrows-up-down','Arrows Up Down'],
['solid/arrows-up-down-left-right','Arrows Up Down Left Right'],
['solid/arrows-up-to-line','Arrows Up To Line'],
['brands/artstation','Artstation'],
['solid/asterisk','Asterisk'],
['brands/asymmetrik','Asymmetrik'],
['solid/at','At'],
['brands/atlassian','Atlassian'],
['solid/atom','Atom'],
['brands/audible','Audible'],
['solid/audio-description','Audio Description'],
['solid/austral-sign','Austral Sign'],
['brands/autoprefixer','Autoprefixer'],
['brands/avianex','Avianex'],
['brands/aviato','Aviato'],
['solid/award','Award'],
['brands/aws','Aws'],
['solid/b','B'],
['solid/baby','Baby'],
['solid/baby-carriage','Baby Carriage'],
['solid/backward','Backward'],
['solid/backward-fast','Backward Fast'],
['solid/backward-step','Backward Step'],
['solid/bacon','Bacon'],
['solid/bacteria','Bacteria'],
['solid/bacterium','Bacterium'],
['solid/bag-shopping','Bag Shopping'],
['solid/bahai','Bahai'],
['solid/baht-sign','Baht Sign'],
['solid/ban','Ban'],
['solid/ban-smoking','Ban Smoking'],
['solid/bandage','Bandage'],
['brands/bandcamp','Bandcamp'],
['solid/bangladeshi-taka-sign','Bangladeshi Taka Sign'],
['solid/barcode','Barcode'],
['solid/bars','Bars'],
['solid/bars-progress','Bars Progress'],
['solid/bars-staggered','Bars Staggered'],
['solid/baseball','Baseball'],
['solid/baseball-bat-ball','Baseball Bat Ball'],
['solid/basket-shopping','Basket Shopping'],
['solid/basketball','Basketball'],
['solid/bath','Bath'],
['solid/battery-empty','Battery Empty'],
['solid/battery-full','Battery Full'],
['solid/battery-half','Battery Half'],
['solid/battery-quarter','Battery Quarter'],
['solid/battery-three-quarters','Battery Three Quarters'],
['brands/battle-net','Battle Net'],
['solid/bed','Bed'],
['solid/bed-pulse','Bed Pulse'],
['solid/beer-mug-empty','Beer Mug Empty'],
['brands/behance','Behance'],
['regular/bell','Bell'],
['solid/bell','Bell'],
['solid/bell-concierge','Bell Concierge'],
['regular/bell-slash','Bell Slash'],
['solid/bell-slash','Bell Slash'],
['solid/bezier-curve','Bezier Curve'],
['solid/bicycle','Bicycle'],
['brands/bilibili','Bilibili'],
['brands/bimobject','Bimobject'],
['solid/binoculars','Binoculars'],
['solid/biohazard','Biohazard'],
['brands/bitbucket','Bitbucket'],
['brands/bitcoin','Bitcoin'],
['solid/bitcoin-sign','Bitcoin Sign'],
['brands/bity','Bity'],
['brands/black-tie','Black Tie'],
['brands/blackberry','Blackberry'],
['solid/blender','Blender'],
['solid/blender-phone','Blender Phone'],
['solid/blog','Blog'],
['brands/blogger','Blogger'],
['brands/blogger-b','Blogger B'],
['brands/bluesky','Bluesky'],
['brands/bluetooth','Bluetooth'],
['brands/bluetooth-b','Bluetooth B'],
['brands/board-game-geek','Board Game Geek'],
['solid/bold','Bold'],
['solid/bolt','Bolt'],
['solid/bolt-lightning','Bolt Lightning'],
['solid/bomb','Bomb'],
['solid/bone','Bone'],
['solid/bong','Bong'],
['solid/book','Book'],
['solid/book-atlas','Book Atlas'],
['solid/book-bible','Book Bible'],
['solid/book-bookmark','Book Bookmark'],
['solid/book-journal-whills','Book Journal Whills'],
['solid/book-medical','Book Medical'],
['solid/book-open','Book Open'],
['solid/book-open-reader','Book Open Reader'],
['solid/book-quran','Book Quran'],
['solid/book-skull','Book Skull'],
['solid/book-tanakh','Book Tanakh'],
['regular/bookmark','Bookmark'],
['solid/bookmark','Bookmark'],
['brands/bootstrap','Bootstrap'],
['solid/border-all','Border All'],
['solid/border-none','Border None'],
['solid/border-top-left','Border Top Left'],
['solid/bore-hole','Bore Hole'],
['brands/bots','Bots'],
['solid/bottle-droplet','Bottle Droplet'],
['solid/bottle-water','Bottle Water'],
['solid/bowl-food','Bowl Food'],
['solid/bowl-rice','Bowl Rice'],
['solid/bowling-ball','Bowling Ball'],
['solid/box','Box'],
['solid/box-archive','Box Archive'],
['solid/box-open','Box Open'],
['solid/box-tissue','Box Tissue'],
['solid/boxes-packing','Boxes Packing'],
['solid/boxes-stacked','Boxes Stacked'],
['solid/braille','Braille'],
['solid/brain','Brain'],
['brands/brave','Brave'],
['brands/brave-reverse','Brave Reverse'],
['solid/brazilian-real-sign','Brazilian Real Sign'],
['solid/bread-slice','Bread Slice'],
['solid/bridge','Bridge'],
['solid/bridge-circle-check','Bridge Circle Check'],
['solid/bridge-circle-exclamation','Bridge Circle Exclamation'],
['solid/bridge-circle-xmark','Bridge Circle Xmark'],
['solid/bridge-lock','Bridge Lock'],
['solid/bridge-water','Bridge Water'],
['solid/briefcase','Briefcase'],
['solid/briefcase-medical','Briefcase Medical'],
['solid/broom','Broom'],
['solid/broom-ball','Broom Ball'],
['solid/brush','Brush'],
['brands/btc','Btc'],
['solid/bucket','Bucket'],
['brands/buffer','Buffer'],
['solid/bug','Bug'],
['solid/bug-slash','Bug Slash'],
['solid/bugs','Bugs'],
['brands/build-awesome','Build Awesome'],
['regular/building','Building'],
['solid/building','Building'],
['solid/building-circle-arrow-right','Building Circle Arrow Right'],
['solid/building-circle-check','Building Circle Check'],
['solid/building-circle-exclamation','Building Circle Exclamation'],
['solid/building-circle-xmark','Building Circle Xmark'],
['solid/building-columns','Building Columns'],
['solid/building-flag','Building Flag'],
['solid/building-lock','Building Lock'],
['solid/building-ngo','Building Ngo'],
['solid/building-shield','Building Shield'],
['solid/building-un','Building Un'],
['solid/building-user','Building User'],
['solid/building-wheat','Building Wheat'],
['solid/bullhorn','Bullhorn'],
['solid/bullseye','Bullseye'],
['solid/burger','Burger'],
['brands/buromobelexperte','Buromobelexperte'],
['solid/burst','Burst'],
['solid/bus','Bus'],
['solid/bus-side','Bus Side'],
['solid/bus-simple','Bus Simple'],
['solid/business-time','Business Time'],
['brands/buy-n-large','Buy N Large'],
['brands/buysellads','Buysellads'],
['solid/c','C'],
['solid/cable-car','Cable Car'],
['solid/cake-candles','Cake Candles'],
['solid/calculator','Calculator'],
['regular/calendar','Calendar'],
['solid/calendar','Calendar'],
['regular/calendar-check','Calendar Check'],
['solid/calendar-check','Calendar Check'],
['solid/calendar-day','Calendar Day'],
['regular/calendar-days','Calendar Days'],
['solid/calendar-days','Calendar Days'],
['regular/calendar-minus','Calendar Minus'],
['solid/calendar-minus','Calendar Minus'],
['regular/calendar-plus','Calendar Plus'],
['solid/calendar-plus','Calendar Plus'],
['solid/calendar-week','Calendar Week'],
['regular/calendar-xmark','Calendar Xmark'],
['solid/calendar-xmark','Calendar Xmark'],
['regular/camera','Camera'],
['solid/camera','Camera'],
['solid/camera-retro','Camera Retro'],
['solid/camera-rotate','Camera Rotate'],
['solid/campground','Campground'],
['brands/canadian-maple-leaf','Canadian Maple Leaf'],
['solid/cancer','Cancer'],
['solid/candy-cane','Candy Cane'],
['solid/cannabis','Cannabis'],
['solid/capricorn','Capricorn'],
['solid/capsules','Capsules'],
['solid/car','Car'],
['solid/car-battery','Car Battery'],
['solid/car-burst','Car Burst'],
['solid/car-on','Car On'],
['solid/car-rear','Car Rear'],
['solid/car-side','Car Side'],
['solid/car-tunnel','Car Tunnel'],
['solid/caravan','Caravan'],
['solid/caret-down','Caret Down'],
['solid/caret-left','Caret Left'],
['solid/caret-right','Caret Right'],
['solid/caret-up','Caret Up'],
['solid/carrot','Carrot'],
['solid/cart-arrow-down','Cart Arrow Down'],
['solid/cart-flatbed','Cart Flatbed'],
['solid/cart-flatbed-suitcase','Cart Flatbed Suitcase'],
['solid/cart-plus','Cart Plus'],
['solid/cart-shopping','Cart Shopping'],
['brands/cash-app','Cash App'],
['solid/cash-register','Cash Register'],
['solid/cat','Cat'],
['brands/cc-amazon-pay','Cc Amazon Pay'],
['brands/cc-amex','Cc Amex'],
['brands/cc-apple-pay','Cc Apple Pay'],
['brands/cc-diners-club','Cc Diners Club'],
['brands/cc-discover','Cc Discover'],
['brands/cc-jcb','Cc Jcb'],
['brands/cc-mastercard','Cc Mastercard'],
['brands/cc-paypal','Cc Paypal'],
['brands/cc-stripe','Cc Stripe'],
['brands/cc-visa','Cc Visa'],
['solid/cedi-sign','Cedi Sign'],
['solid/cent-sign','Cent Sign'],
['brands/centercode','Centercode'],
['brands/centos','Centos'],
['solid/certificate','Certificate'],
['solid/chair','Chair'],
['solid/chalkboard','Chalkboard'],
['solid/chalkboard-user','Chalkboard User'],
['solid/champagne-glasses','Champagne Glasses'],
['solid/charging-station','Charging Station'],
['solid/chart-area','Chart Area'],
['regular/chart-bar','Chart Bar'],
['solid/chart-bar','Chart Bar'],
['solid/chart-column','Chart Column'],
['solid/chart-diagram','Chart Diagram'],
['solid/chart-gantt','Chart Gantt'],
['solid/chart-line','Chart Line'],
['solid/chart-pie','Chart Pie'],
['solid/chart-simple','Chart Simple'],
['solid/check','Check'],
['solid/check-double','Check Double'],
['solid/check-to-slot','Check To Slot'],
['solid/cheese','Cheese'],
['solid/chess','Chess'],
['regular/chess-bishop','Chess Bishop'],
['solid/chess-bishop','Chess Bishop'],
['solid/chess-board','Chess Board'],
['regular/chess-king','Chess King'],
['solid/chess-king','Chess King'],
['regular/chess-knight','Chess Knight'],
['solid/chess-knight','Chess Knight'],
['regular/chess-pawn','Chess Pawn'],
['solid/chess-pawn','Chess Pawn'],
['regular/chess-queen','Chess Queen'],
['solid/chess-queen','Chess Queen'],
['regular/chess-rook','Chess Rook'],
['solid/chess-rook','Chess Rook'],
['solid/chevron-down','Chevron Down'],
['solid/chevron-left','Chevron Left'],
['solid/chevron-right','Chevron Right'],
['solid/chevron-up','Chevron Up'],
['solid/child','Child'],
['solid/child-combatant','Child Combatant'],
['solid/child-dress','Child Dress'],
['solid/child-reaching','Child Reaching'],
['solid/children','Children'],
['brands/chrome','Chrome'],
['brands/chromecast','Chromecast'],
['solid/church','Church'],
['regular/circle','Circle'],
['solid/circle','Circle'],
['solid/circle-arrow-down','Circle Arrow Down'],
['solid/circle-arrow-left','Circle Arrow Left'],
['solid/circle-arrow-right','Circle Arrow Right'],
['solid/circle-arrow-up','Circle Arrow Up'],
['regular/circle-check','Circle Check'],
['solid/circle-check','Circle Check'],
['solid/circle-chevron-down','Circle Chevron Down'],
['solid/circle-chevron-left','Circle Chevron Left'],
['solid/circle-chevron-right','Circle Chevron Right'],
['solid/circle-chevron-up','Circle Chevron Up'],
['solid/circle-dollar-to-slot','Circle Dollar To Slot'],
['regular/circle-dot','Circle Dot'],
['solid/circle-dot','Circle Dot'],
['regular/circle-down','Circle Down'],
['solid/circle-down','Circle Down'],
['solid/circle-exclamation','Circle Exclamation'],
['solid/circle-h','Circle H'],
['solid/circle-half-stroke','Circle Half Stroke'],
['solid/circle-info','Circle Info'],
['regular/circle-left','Circle Left'],
['solid/circle-left','Circle Left'],
['solid/circle-minus','Circle Minus'],
['solid/circle-nodes','Circle Nodes'],
['solid/circle-notch','Circle Notch'],
['regular/circle-pause','Circle Pause'],
['solid/circle-pause','Circle Pause'],
['regular/circle-play','Circle Play'],
['solid/circle-play','Circle Play'],
['solid/circle-plus','Circle Plus'],
['regular/circle-question','Circle Question'],
['solid/circle-question','Circle Question'],
['solid/circle-radiation','Circle Radiation'],
['regular/circle-right','Circle Right'],
['solid/circle-right','Circle Right'],
['regular/circle-stop','Circle Stop'],
['solid/circle-stop','Circle Stop'],
['regular/circle-up','Circle Up'],
['solid/circle-up','Circle Up'],
['regular/circle-user','Circle User'],
['solid/circle-user','Circle User'],
['regular/circle-xmark','Circle Xmark'],
['solid/circle-xmark','Circle Xmark'],
['brands/circle-zulip','Circle Zulip'],
['solid/city','City'],
['solid/clapperboard','Clapperboard'],
['brands/claude','Claude'],
['regular/clipboard','Clipboard'],
['solid/clipboard','Clipboard'],
['solid/clipboard-check','Clipboard Check'],
['solid/clipboard-list','Clipboard List'],
['solid/clipboard-question','Clipboard Question'],
['solid/clipboard-user','Clipboard User'],
['regular/clock','Clock'],
['solid/clock','Clock'],
['solid/clock-rotate-left','Clock Rotate Left'],
['regular/clone','Clone'],
['solid/clone','Clone'],
['regular/closed-captioning','Closed Captioning'],
['solid/closed-captioning','Closed Captioning'],
['solid/closed-captioning-slash','Closed Captioning Slash'],
['regular/cloud','Cloud'],
['solid/cloud','Cloud'],
['solid/cloud-arrow-down','Cloud Arrow Down'],
['solid/cloud-arrow-up','Cloud Arrow Up'],
['solid/cloud-bolt','Cloud Bolt'],
['solid/cloud-meatball','Cloud Meatball'],
['solid/cloud-moon','Cloud Moon'],
['solid/cloud-moon-rain','Cloud Moon Rain'],
['solid/cloud-rain','Cloud Rain'],
['solid/cloud-showers-heavy','Cloud Showers Heavy'],
['solid/cloud-showers-water','Cloud Showers Water'],
['solid/cloud-sun','Cloud Sun'],
['solid/cloud-sun-rain','Cloud Sun Rain'],
['brands/cloudflare','Cloudflare'],
['brands/cloudscale','Cloudscale'],
['brands/cloudsmith','Cloudsmith'],
['brands/cloudversify','Cloudversify'],
['solid/clover','Clover'],
['brands/cmplid','Cmplid'],
['solid/code','Code'],
['solid/code-branch','Code Branch'],
['solid/code-commit','Code Commit'],
['solid/code-compare','Code Compare'],
['solid/code-fork','Code Fork'],
['solid/code-merge','Code Merge'],
['solid/code-pull-request','Code Pull Request'],
['brands/codeberg','Codeberg'],
['brands/codepen','Codepen'],
['brands/codiepie','Codiepie'],
['solid/coins','Coins'],
['solid/colon-sign','Colon Sign'],
['regular/comment','Comment'],
['solid/comment','Comment'],
['solid/comment-dollar','Comment Dollar'],
['regular/comment-dots','Comment Dots'],
['solid/comment-dots','Comment Dots'],
['solid/comment-medical','Comment Medical'],
['solid/comment-nodes','Comment Nodes'],
['solid/comment-slash','Comment Slash'],
['solid/comment-sms','Comment Sms'],
['regular/comments','Comments'],
['solid/comments','Comments'],
['solid/comments-dollar','Comments Dollar'],
['solid/compact-disc','Compact Disc'],
['regular/compass','Compass'],
['solid/compass','Compass'],
['solid/compass-drafting','Compass Drafting'],
['solid/compress','Compress'],
['solid/computer','Computer'],
['solid/computer-mouse','Computer Mouse'],
['brands/confluence','Confluence'],
['brands/connectdevelop','Connectdevelop'],
['brands/contao','Contao'],
['solid/cookie','Cookie'],
['solid/cookie-bite','Cookie Bite'],
['brands/copilot','Copilot'],
['regular/copy','Copy'],
['solid/copy','Copy'],
['regular/copyright','Copyright'],
['solid/copyright','Copyright'],
['brands/cotton-bureau','Cotton Bureau'],
['solid/couch','Couch'],
['solid/cow','Cow'],
['brands/cpanel','Cpanel'],
['brands/creative-commons','Creative Commons'],
['brands/creative-commons-by','Creative Commons By'],
['brands/creative-commons-nc','Creative Commons Nc'],
['brands/creative-commons-nc-eu','Creative Commons Nc Eu'],
['brands/creative-commons-nc-jp','Creative Commons Nc Jp'],
['brands/creative-commons-nd','Creative Commons Nd'],
['brands/creative-commons-pd','Creative Commons Pd'],
['brands/creative-commons-pd-alt','Creative Commons Pd Alt'],
['brands/creative-commons-remix','Creative Commons Remix'],
['brands/creative-commons-sa','Creative Commons Sa'],
['brands/creative-commons-sampling','Creative Commons Sampling'],
['brands/creative-commons-sampling-plus','Creative Commons Sampling Plus'],
['brands/creative-commons-share','Creative Commons Share'],
['brands/creative-commons-zero','Creative Commons Zero'],
['regular/credit-card','Credit Card'],
['solid/credit-card','Credit Card'],
['brands/critical-role','Critical Role'],
['solid/crop','Crop'],
['solid/crop-simple','Crop Simple'],
['solid/cross','Cross'],
['solid/crosshairs','Crosshairs'],
['solid/crow','Crow'],
['solid/crown','Crown'],
['solid/crutch','Crutch'],
['solid/cruzeiro-sign','Cruzeiro Sign'],
['brands/css','Css'],
['brands/css3','Css3'],
['brands/css3-alt','Css3 Alt'],
['solid/cube','Cube'],
['solid/cubes','Cubes'],
['solid/cubes-stacked','Cubes Stacked'],
['brands/cuttlefish','Cuttlefish'],
['solid/d','D'],
['brands/d-and-d','D And D'],
['brands/d-and-d-beyond','D And D Beyond'],
['brands/dailymotion','Dailymotion'],
['brands/dart-lang','Dart Lang'],
['brands/dashcube','Dashcube'],
['solid/database','Database'],
['brands/debian','Debian'],
['brands/deezer','Deezer'],
['solid/delete-left','Delete Left'],
['brands/delicious','Delicious'],
['solid/democrat','Democrat'],
['brands/deploydog','Deploydog'],
['brands/deskpro','Deskpro'],
['solid/desktop','Desktop'],
['brands/dev','Dev'],
['brands/deviantart','Deviantart'],
['brands/devpost','Devpost'],
['solid/dharmachakra','Dharmachakra'],
['brands/dhl','Dhl'],
['solid/diagram-next','Diagram Next'],
['solid/diagram-predecessor','Diagram Predecessor'],
['solid/diagram-project','Diagram Project'],
['solid/diagram-successor','Diagram Successor'],
['solid/diamond','Diamond'],
['solid/diamond-turn-right','Diamond Turn Right'],
['brands/diaspora','Diaspora'],
['solid/dice','Dice'],
['solid/dice-d20','Dice D20'],
['solid/dice-d6','Dice D6'],
['solid/dice-five','Dice Five'],
['solid/dice-four','Dice Four'],
['solid/dice-one','Dice One'],
['solid/dice-six','Dice Six'],
['solid/dice-three','Dice Three'],
['solid/dice-two','Dice Two'],
['brands/digg','Digg'],
['brands/digital-ocean','Digital Ocean'],
['brands/discord','Discord'],
['brands/discourse','Discourse'],
['solid/disease','Disease'],
['solid/display','Display'],
['brands/disqus','Disqus'],
['solid/divide','Divide'],
['solid/dna','Dna'],
['brands/dochub','Dochub'],
['brands/docker','Docker'],
['solid/dog','Dog'],
['brands/dolibarr','Dolibarr'],
['solid/dollar-sign','Dollar Sign'],
['solid/dolly','Dolly'],
['solid/dong-sign','Dong Sign'],
['solid/door-closed','Door Closed'],
['solid/door-open','Door Open'],
['solid/dove','Dove'],
['solid/down-left-and-up-right-to-center','Down Left And Up Right To Center'],
['solid/down-long','Down Long'],
['solid/download','Download'],
['brands/draft2digital','Draft2digital'],
['solid/dragon','Dragon'],
['solid/draw-polygon','Draw Polygon'],
['brands/dribbble','Dribbble'],
['brands/dropbox','Dropbox'],
['solid/droplet','Droplet'],
['solid/droplet-slash','Droplet Slash'],
['solid/drum','Drum'],
['solid/drum-steelpan','Drum Steelpan'],
['solid/drumstick-bite','Drumstick Bite'],
['brands/drupal','Drupal'],
['solid/dumbbell','Dumbbell'],
['solid/dumpster','Dumpster'],
['solid/dumpster-fire','Dumpster Fire'],
['solid/dungeon','Dungeon'],
['brands/duolingo','Duolingo'],
['brands/dyalog','Dyalog'],
['solid/e','E'],
['solid/ear-deaf','Ear Deaf'],
['solid/ear-listen','Ear Listen'],
['brands/earlybirds','Earlybirds'],
['solid/earth-africa','Earth Africa'],
['solid/earth-americas','Earth Americas'],
['solid/earth-asia','Earth Asia'],
['solid/earth-europe','Earth Europe'],
['solid/earth-oceania','Earth Oceania'],
['brands/ebay','Ebay'],
['brands/edge','Edge'],
['brands/edge-legacy','Edge Legacy'],
['solid/egg','Egg'],
['solid/eject','Eject'],
['brands/elementor','Elementor'],
['solid/elevator','Elevator'],
['brands/eleventy','Eleventy'],
['solid/ellipsis','Ellipsis'],
['solid/ellipsis-vertical','Ellipsis Vertical'],
['brands/ello','Ello'],
['brands/ember','Ember'],
['brands/empire','Empire'],
['regular/envelope','Envelope'],
['solid/envelope','Envelope'],
['solid/envelope-circle-check','Envelope Circle Check'],
['regular/envelope-open','Envelope Open'],
['solid/envelope-open','Envelope Open'],
['solid/envelope-open-text','Envelope Open Text'],
['solid/envelopes-bulk','Envelopes Bulk'],
['brands/envira','Envira'],
['solid/equals','Equals'],
['solid/eraser','Eraser'],
['brands/erlang','Erlang'],
['brands/ethereum','Ethereum'],
['solid/ethernet','Ethernet'],
['brands/etsy','Etsy'],
['solid/euro-sign','Euro Sign'],
['brands/evernote','Evernote'],
['solid/exclamation','Exclamation'],
['solid/expand','Expand'],
['brands/expeditedssl','Expeditedssl'],
['solid/explosion','Explosion'],
['regular/eye','Eye'],
['solid/eye','Eye'],
['solid/eye-dropper','Eye Dropper'],
['solid/eye-low-vision','Eye Low Vision'],
['regular/eye-slash','Eye Slash'],
['solid/eye-slash','Eye Slash'],
['solid/f','F'],
['regular/face-angry','Face Angry'],
['solid/face-angry','Face Angry'],
['regular/face-dizzy','Face Dizzy'],
['solid/face-dizzy','Face Dizzy'],
['regular/face-flushed','Face Flushed'],
['solid/face-flushed','Face Flushed'],
['regular/face-frown','Face Frown'],
['solid/face-frown','Face Frown'],
['regular/face-frown-open','Face Frown Open'],
['solid/face-frown-open','Face Frown Open'],
['regular/face-grimace','Face Grimace'],
['solid/face-grimace','Face Grimace'],
['regular/face-grin','Face Grin'],
['solid/face-grin','Face Grin'],
['regular/face-grin-beam','Face Grin Beam'],
['solid/face-grin-beam','Face Grin Beam'],
['regular/face-grin-beam-sweat','Face Grin Beam Sweat'],
['solid/face-grin-beam-sweat','Face Grin Beam Sweat'],
['regular/face-grin-hearts','Face Grin Hearts'],
['solid/face-grin-hearts','Face Grin Hearts'],
['regular/face-grin-squint','Face Grin Squint'],
['solid/face-grin-squint','Face Grin Squint'],
['regular/face-grin-squint-tears','Face Grin Squint Tears'],
['solid/face-grin-squint-tears','Face Grin Squint Tears'],
['regular/face-grin-stars','Face Grin Stars'],
['solid/face-grin-stars','Face Grin Stars'],
['regular/face-grin-tears','Face Grin Tears'],
['solid/face-grin-tears','Face Grin Tears'],
['regular/face-grin-tongue','Face Grin Tongue'],
['solid/face-grin-tongue','Face Grin Tongue'],
['regular/face-grin-tongue-squint','Face Grin Tongue Squint'],
['solid/face-grin-tongue-squint','Face Grin Tongue Squint'],
['regular/face-grin-tongue-wink','Face Grin Tongue Wink'],
['solid/face-grin-tongue-wink','Face Grin Tongue Wink'],
['regular/face-grin-wide','Face Grin Wide'],
['solid/face-grin-wide','Face Grin Wide'],
['regular/face-grin-wink','Face Grin Wink'],
['solid/face-grin-wink','Face Grin Wink'],
['regular/face-kiss','Face Kiss'],
['solid/face-kiss','Face Kiss'],
['regular/face-kiss-beam','Face Kiss Beam'],
['solid/face-kiss-beam','Face Kiss Beam'],
['regular/face-kiss-wink-heart','Face Kiss Wink Heart'],
['solid/face-kiss-wink-heart','Face Kiss Wink Heart'],
['regular/face-laugh','Face Laugh'],
['solid/face-laugh','Face Laugh'],
['regular/face-laugh-beam','Face Laugh Beam'],
['solid/face-laugh-beam','Face Laugh Beam'],
['regular/face-laugh-squint','Face Laugh Squint'],
['solid/face-laugh-squint','Face Laugh Squint'],
['regular/face-laugh-wink','Face Laugh Wink'],
['solid/face-laugh-wink','Face Laugh Wink'],
['regular/face-meh','Face Meh'],
['solid/face-meh','Face Meh'],
['regular/face-meh-blank','Face Meh Blank'],
['solid/face-meh-blank','Face Meh Blank'],
['regular/face-rolling-eyes','Face Rolling Eyes'],
['solid/face-rolling-eyes','Face Rolling Eyes'],
['regular/face-sad-cry','Face Sad Cry'],
['solid/face-sad-cry','Face Sad Cry'],
['regular/face-sad-tear','Face Sad Tear'],
['solid/face-sad-tear','Face Sad Tear'],
['regular/face-smile','Face Smile'],
['solid/face-smile','Face Smile'],
['regular/face-smile-beam','Face Smile Beam'],
['solid/face-smile-beam','Face Smile Beam'],
['regular/face-smile-wink','Face Smile Wink'],
['solid/face-smile-wink','Face Smile Wink'],
['regular/face-surprise','Face Surprise'],
['solid/face-surprise','Face Surprise'],
['regular/face-tired','Face Tired'],
['solid/face-tired','Face Tired'],
['brands/facebook','Facebook'],
['brands/facebook-f','Facebook F'],
['brands/facebook-messenger','Facebook Messenger'],
['solid/fan','Fan'],
['brands/fantasy-flight-games','Fantasy Flight Games'],
['solid/faucet','Faucet'],
['solid/faucet-drip','Faucet Drip'],
['solid/fax','Fax'],
['solid/feather','Feather'],
['solid/feather-pointed','Feather Pointed'],
['brands/fedex','Fedex'],
['brands/fediverse','Fediverse'],
['brands/fedora','Fedora'],
['solid/ferry','Ferry'],
['brands/figma','Figma'],
['regular/file','File'],
['solid/file','File'],
['solid/file-arrow-down','File Arrow Down'],
['solid/file-arrow-up','File Arrow Up'],
['regular/file-audio','File Audio'],
['solid/file-audio','File Audio'],
['solid/file-circle-check','File Circle Check'],
['solid/file-circle-exclamation','File Circle Exclamation'],
['solid/file-circle-minus','File Circle Minus'],
['solid/file-circle-plus','File Circle Plus'],
['solid/file-circle-question','File Circle Question'],
['solid/file-circle-xmark','File Circle Xmark'],
['regular/file-code','File Code'],
['solid/file-code','File Code'],
['solid/file-contract','File Contract'],
['solid/file-csv','File Csv'],
['regular/file-excel','File Excel'],
['solid/file-excel','File Excel'],
['solid/file-export','File Export'],
['solid/file-fragment','File Fragment'],
['solid/file-half-dashed','File Half Dashed'],
['regular/file-image','File Image'],
['solid/file-image','File Image'],
['solid/file-import','File Import'],
['solid/file-invoice','File Invoice'],
['solid/file-invoice-dollar','File Invoice Dollar'],
['regular/file-lines','File Lines'],
['solid/file-lines','File Lines'],
['solid/file-medical','File Medical'],
['regular/file-pdf','File Pdf'],
['solid/file-pdf','File Pdf'],
['solid/file-pen','File Pen'],
['regular/file-powerpoint','File Powerpoint'],
['solid/file-powerpoint','File Powerpoint'],
['solid/file-prescription','File Prescription'],
['solid/file-shield','File Shield'],
['solid/file-signature','File Signature'],
['regular/file-video','File Video'],
['solid/file-video','File Video'],
['solid/file-waveform','File Waveform'],
['regular/file-word','File Word'],
['solid/file-word','File Word'],
['regular/file-zipper','File Zipper'],
['solid/file-zipper','File Zipper'],
['brands/files-pinwheel','Files Pinwheel'],
['solid/fill','Fill'],
['solid/fill-drip','Fill Drip'],
['solid/film','Film'],
['solid/filter','Filter'],
['solid/filter-circle-dollar','Filter Circle Dollar'],
['solid/filter-circle-xmark','Filter Circle Xmark'],
['solid/fingerprint','Fingerprint'],
['solid/fire','Fire'],
['solid/fire-burner','Fire Burner'],
['solid/fire-extinguisher','Fire Extinguisher'],
['solid/fire-flame-curved','Fire Flame Curved'],
['solid/fire-flame-simple','Fire Flame Simple'],
['brands/firefox','Firefox'],
['brands/firefox-browser','Firefox Browser'],
['brands/first-order','First Order'],
['brands/first-order-alt','First Order Alt'],
['brands/firstdraft','Firstdraft'],
['solid/fish','Fish'],
['solid/fish-fins','Fish Fins'],
['regular/flag','Flag'],
['solid/flag','Flag'],
['solid/flag-checkered','Flag Checkered'],
['solid/flag-usa','Flag Usa'],
['solid/flask','Flask'],
['solid/flask-vial','Flask Vial'],
['brands/flickr','Flickr'],
['brands/flipboard','Flipboard'],
['regular/floppy-disk','Floppy Disk'],
['solid/floppy-disk','Floppy Disk'],
['solid/florin-sign','Florin Sign'],
['brands/flutter','Flutter'],
['brands/fly','Fly'],
['regular/folder','Folder'],
['solid/folder','Folder'],
['regular/folder-closed','Folder Closed'],
['solid/folder-closed','Folder Closed'],
['solid/folder-minus','Folder Minus'],
['regular/folder-open','Folder Open'],
['solid/folder-open','Folder Open'],
['solid/folder-plus','Folder Plus'],
['solid/folder-tree','Folder Tree'],
['solid/font','Font'],
['brands/font-awesome','Font Awesome'],
['regular/font-awesome','Font Awesome'],
['solid/font-awesome','Font Awesome'],
['brands/fonticons','Fonticons'],
['brands/fonticons-fi','Fonticons Fi'],
['solid/football','Football'],
['brands/forgejo','Forgejo'],
['brands/fort-awesome','Fort Awesome'],
['brands/fort-awesome-alt','Fort Awesome Alt'],
['brands/forumbee','Forumbee'],
['solid/forward','Forward'],
['solid/forward-fast','Forward Fast'],
['solid/forward-step','Forward Step'],
['brands/foursquare','Foursquare'],
['solid/franc-sign','Franc Sign'],
['brands/free-code-camp','Free Code Camp'],
['brands/freebsd','Freebsd'],
['solid/frog','Frog'],
['brands/fulcrum','Fulcrum'],
['regular/futbol','Futbol'],
['solid/futbol','Futbol'],
['solid/g','G'],
['brands/galactic-republic','Galactic Republic'],
['brands/galactic-senate','Galactic Senate'],
['solid/gamepad','Gamepad'],
['solid/gas-pump','Gas Pump'],
['solid/gauge','Gauge'],
['solid/gauge-high','Gauge High'],
['solid/gauge-simple','Gauge Simple'],
['solid/gauge-simple-high','Gauge Simple High'],
['solid/gavel','Gavel'],
['solid/gear','Gear'],
['solid/gears','Gears'],
['regular/gem','Gem'],
['solid/gem','Gem'],
['solid/gemini','Gemini'],
['solid/genderless','Genderless'],
['brands/get-pocket','Get Pocket'],
['brands/gg','Gg'],
['brands/gg-circle','Gg Circle'],
['solid/ghost','Ghost'],
['solid/gift','Gift'],
['solid/gifts','Gifts'],
['brands/git','Git'],
['brands/git-alt','Git Alt'],
['brands/gitee','Gitee'],
['brands/github','Github'],
['brands/github-alt','Github Alt'],
['brands/gitkraken','Gitkraken'],
['brands/gitlab','Gitlab'],
['brands/gitter','Gitter'],
['solid/glass-water','Glass Water'],
['solid/glass-water-droplet','Glass Water Droplet'],
['solid/glasses','Glasses'],
['brands/glide','Glide'],
['brands/glide-g','Glide G'],
['brands/globaleaks','Globaleaks'],
['solid/globe','Globe'],
['brands/gofore','Gofore'],
['brands/golang','Golang'],
['solid/golf-ball-tee','Golf Ball Tee'],
['brands/goodreads','Goodreads'],
['brands/goodreads-g','Goodreads G'],
['brands/google','Google'],
['brands/google-drive','Google Drive'],
['brands/google-pay','Google Pay'],
['brands/google-play','Google Play'],
['brands/google-plus','Google Plus'],
['brands/google-plus-g','Google Plus G'],
['brands/google-scholar','Google Scholar'],
['brands/google-wallet','Google Wallet'],
['solid/gopuram','Gopuram'],
['solid/graduation-cap','Graduation Cap'],
['brands/gratipay','Gratipay'],
['brands/grav','Grav'],
['solid/greater-than','Greater Than'],
['solid/greater-than-equal','Greater Than Equal'],
['solid/grip','Grip'],
['solid/grip-lines','Grip Lines'],
['solid/grip-lines-vertical','Grip Lines Vertical'],
['solid/grip-vertical','Grip Vertical'],
['brands/gripfire','Gripfire'],
['solid/group-arrows-rotate','Group Arrows Rotate'],
['brands/grunt','Grunt'],
['solid/guarani-sign','Guarani Sign'],
['brands/guilded','Guilded'],
['solid/guitar','Guitar'],
['brands/gulp','Gulp'],
['solid/gun','Gun'],
['solid/h','H'],
['brands/hacker-news','Hacker News'],
['brands/hackerrank','Hackerrank'],
['solid/hammer','Hammer'],
['solid/hamsa','Hamsa'],
['regular/hand','Hand'],
['solid/hand','Hand'],
['regular/hand-back-fist','Hand Back Fist'],
['solid/hand-back-fist','Hand Back Fist'],
['solid/hand-dots','Hand Dots'],
['solid/hand-fist','Hand Fist'],
['solid/hand-holding','Hand Holding'],
['solid/hand-holding-dollar','Hand Holding Dollar'],
['solid/hand-holding-droplet','Hand Holding Droplet'],
['solid/hand-holding-hand','Hand Holding Hand'],
['solid/hand-holding-heart','Hand Holding Heart'],
['solid/hand-holding-medical','Hand Holding Medical'],
['regular/hand-lizard','Hand Lizard'],
['solid/hand-lizard','Hand Lizard'],
['solid/hand-middle-finger','Hand Middle Finger'],
['regular/hand-peace','Hand Peace'],
['solid/hand-peace','Hand Peace'],
['regular/hand-point-down','Hand Point Down'],
['solid/hand-point-down','Hand Point Down'],
['regular/hand-point-left','Hand Point Left'],
['solid/hand-point-left','Hand Point Left'],
['regular/hand-point-right','Hand Point Right'],
['solid/hand-point-right','Hand Point Right'],
['regular/hand-point-up','Hand Point Up'],
['solid/hand-point-up','Hand Point Up'],
['regular/hand-pointer','Hand Pointer'],
['solid/hand-pointer','Hand Pointer'],
['regular/hand-scissors','Hand Scissors'],
['solid/hand-scissors','Hand Scissors'],
['solid/hand-sparkles','Hand Sparkles'],
['regular/hand-spock','Hand Spock'],
['solid/hand-spock','Hand Spock'],
['solid/handcuffs','Handcuffs'],
['solid/hands','Hands'],
['solid/hands-asl-interpreting','Hands Asl Interpreting'],
['solid/hands-bound','Hands Bound'],
['solid/hands-bubbles','Hands Bubbles'],
['solid/hands-clapping','Hands Clapping'],
['solid/hands-holding','Hands Holding'],
['solid/hands-holding-child','Hands Holding Child'],
['solid/hands-holding-circle','Hands Holding Circle'],
['solid/hands-praying','Hands Praying'],
['regular/handshake','Handshake'],
['solid/handshake','Handshake'],
['solid/handshake-angle','Handshake Angle'],
['solid/handshake-slash','Handshake Slash'],
['solid/hanukiah','Hanukiah'],
['regular/hard-drive','Hard Drive'],
['solid/hard-drive','Hard Drive'],
['brands/hashnode','Hashnode'],
['solid/hashtag','Hashtag'],
['solid/hat-cowboy','Hat Cowboy'],
['solid/hat-cowboy-side','Hat Cowboy Side'],
['solid/hat-wizard','Hat Wizard'],
['solid/head-side-cough','Head Side Cough'],
['solid/head-side-cough-slash','Head Side Cough Slash'],
['solid/head-side-mask','Head Side Mask'],
['solid/head-side-virus','Head Side Virus'],
['solid/heading','Heading'],
['regular/headphones','Headphones'],
['solid/headphones','Headphones'],
['solid/headset','Headset'],
['regular/heart','Heart'],
['solid/heart','Heart'],
['solid/heart-circle-bolt','Heart Circle Bolt'],
['solid/heart-circle-check','Heart Circle Check'],
['solid/heart-circle-exclamation','Heart Circle Exclamation'],
['solid/heart-circle-minus','Heart Circle Minus'],
['solid/heart-circle-plus','Heart Circle Plus'],
['solid/heart-circle-xmark','Heart Circle Xmark'],
['solid/heart-crack','Heart Crack'],
['solid/heart-pulse','Heart Pulse'],
['solid/helicopter','Helicopter'],
['solid/helicopter-symbol','Helicopter Symbol'],
['solid/helmet-safety','Helmet Safety'],
['solid/helmet-un','Helmet Un'],
['solid/hexagon','Hexagon'],
['solid/hexagon-nodes','Hexagon Nodes'],
['solid/hexagon-nodes-bolt','Hexagon Nodes Bolt'],
['solid/highlighter','Highlighter'],
['solid/hill-avalanche','Hill Avalanche'],
['solid/hill-rockslide','Hill Rockslide'],
['solid/hippo','Hippo'],
['brands/hips','Hips'],
['brands/hire-a-helper','Hire A Helper'],
['brands/hive','Hive'],
['solid/hockey-puck','Hockey Puck'],
['solid/holly-berry','Holly Berry'],
['brands/hooli','Hooli'],
['brands/hornbill','Hornbill'],
['solid/horse','Horse'],
['solid/horse-head','Horse Head'],
['regular/hospital','Hospital'],
['solid/hospital','Hospital'],
['solid/hospital-user','Hospital User'],
['solid/hot-tub-person','Hot Tub Person'],
['solid/hotdog','Hotdog'],
['solid/hotel','Hotel'],
['brands/hotjar','Hotjar'],
['regular/hourglass','Hourglass'],
['solid/hourglass','Hourglass'],
['solid/hourglass-end','Hourglass End'],
['regular/hourglass-half','Hourglass Half'],
['solid/hourglass-half','Hourglass Half'],
['solid/hourglass-start','Hourglass Start'],
['regular/house','House'],
['solid/house','House'],
['solid/house-chimney','House Chimney'],
['solid/house-chimney-crack','House Chimney Crack'],
['solid/house-chimney-medical','House Chimney Medical'],
['solid/house-chimney-user','House Chimney User'],
['solid/house-chimney-window','House Chimney Window'],
['solid/house-circle-check','House Circle Check'],
['solid/house-circle-exclamation','House Circle Exclamation'],
['solid/house-circle-xmark','House Circle Xmark'],
['solid/house-crack','House Crack'],
['solid/house-fire','House Fire'],
['solid/house-flag','House Flag'],
['solid/house-flood-water','House Flood Water'],
['solid/house-flood-water-circle-arrow-right','House Flood Water Circle Arrow Right'],
['solid/house-laptop','House Laptop'],
['solid/house-lock','House Lock'],
['solid/house-medical','House Medical'],
['solid/house-medical-circle-check','House Medical Circle Check'],
['solid/house-medical-circle-exclamation','House Medical Circle Exclamation'],
['solid/house-medical-circle-xmark','House Medical Circle Xmark'],
['solid/house-medical-flag','House Medical Flag'],
['solid/house-signal','House Signal'],
['solid/house-tsunami','House Tsunami'],
['solid/house-user','House User'],
['brands/houzz','Houzz'],
['solid/hryvnia-sign','Hryvnia Sign'],
['brands/html5','Html5'],
['brands/hubspot','Hubspot'],
['brands/hugging-face','Hugging Face'],
['solid/hurricane','Hurricane'],
['solid/i','I'],
['solid/i-cursor','I Cursor'],
['solid/ice-cream','Ice Cream'],
['solid/icicles','Icicles'],
['solid/icons','Icons'],
['regular/id-badge','Id Badge'],
['solid/id-badge','Id Badge'],
['regular/id-card','Id Card'],
['solid/id-card','Id Card'],
['solid/id-card-clip','Id Card Clip'],
['brands/ideal','Ideal'],
['solid/igloo','Igloo'],
['regular/image','Image'],
['solid/image','Image'],
['solid/image-portrait','Image Portrait'],
['regular/images','Images'],
['solid/images','Images'],
['brands/imdb','Imdb'],
['solid/inbox','Inbox'],
['solid/indent','Indent'],
['solid/indian-rupee-sign','Indian Rupee Sign'],
['solid/industry','Industry'],
['solid/infinity','Infinity'],
['solid/info','Info'],
['brands/instagram','Instagram'],
['brands/instalod','Instalod'],
['brands/intercom','Intercom'],
['brands/internet-archive','Internet Archive'],
['brands/internet-explorer','Internet Explorer'],
['brands/invision','Invision'],
['brands/ioxhost','Ioxhost'],
['solid/italic','Italic'],
['brands/itch-io','Itch Io'],
['brands/itunes','Itunes'],
['brands/itunes-note','Itunes Note'],
['solid/j','J'],
['solid/jar','Jar'],
['solid/jar-wheat','Jar Wheat'],
['brands/java','Java'],
['solid/jedi','Jedi'],
['brands/jedi-order','Jedi Order'],
['brands/jenkins','Jenkins'],
['solid/jet-fighter','Jet Fighter'],
['solid/jet-fighter-up','Jet Fighter Up'],
['brands/jira','Jira'],
['brands/joget','Joget'],
['solid/joint','Joint'],
['brands/joomla','Joomla'],
['brands/js','Js'],
['brands/jsfiddle','Jsfiddle'],
['solid/jug-detergent','Jug Detergent'],
['brands/julia','Julia'],
['brands/jxl','Jxl'],
['solid/k','K'],
['solid/kaaba','Kaaba'],
['brands/kaggle','Kaggle'],
['brands/kakao-talk','Kakao Talk'],
['solid/key','Key'],
['brands/keybase','Keybase'],
['regular/keyboard','Keyboard'],
['solid/keyboard','Keyboard'],
['brands/keycdn','Keycdn'],
['solid/khanda','Khanda'],
['brands/kickstarter','Kickstarter'],
['brands/kickstarter-k','Kickstarter K'],
['solid/kip-sign','Kip Sign'],
['solid/kit-medical','Kit Medical'],
['solid/kitchen-set','Kitchen Set'],
['solid/kiwi-bird','Kiwi Bird'],
['brands/ko-fi','Ko Fi'],
['brands/korvue','Korvue'],
['brands/kubernetes','Kubernetes'],
['solid/l','L'],
['solid/land-mine-on','Land Mine On'],
['solid/landmark','Landmark'],
['solid/landmark-dome','Landmark Dome'],
['solid/landmark-flag','Landmark Flag'],
['solid/language','Language'],
['solid/laptop','Laptop'],
['solid/laptop-code','Laptop Code'],
['solid/laptop-file','Laptop File'],
['solid/laptop-medical','Laptop Medical'],
['brands/laravel','Laravel'],
['solid/lari-sign','Lari Sign'],
['brands/lastfm','Lastfm'],
['solid/layer-group','Layer Group'],
['solid/leaf','Leaf'],
['brands/leanpub','Leanpub'],
['brands/leetcode','Leetcode'],
['solid/left-long','Left Long'],
['solid/left-right','Left Right'],
['regular/lemon','Lemon'],
['solid/lemon','Lemon'],
['solid/leo','Leo'],
['brands/less','Less'],
['solid/less-than','Less Than'],
['solid/less-than-equal','Less Than Equal'],
['brands/lets-encrypt','Lets Encrypt'],
['brands/letterboxd','Letterboxd'],
['solid/libra','Libra'],
['regular/life-ring','Life Ring'],
['solid/life-ring','Life Ring'],
['regular/lightbulb','Lightbulb'],
['solid/lightbulb','Lightbulb'],
['brands/line','Line'],
['solid/lines-leaning','Lines Leaning'],
['solid/link','Link'],
['solid/link-slash','Link Slash'],
['brands/linkedin','Linkedin'],
['brands/linkedin-in','Linkedin In'],
['brands/linktree','Linktree'],
['brands/linode','Linode'],
['brands/linux','Linux'],
['solid/lira-sign','Lira Sign'],
['solid/list','List'],
['solid/list-check','List Check'],
['solid/list-ol','List Ol'],
['solid/list-ul','List Ul'],
['solid/litecoin-sign','Litecoin Sign'],
['solid/location-arrow','Location Arrow'],
['solid/location-crosshairs','Location Crosshairs'],
['solid/location-dot','Location Dot'],
['solid/location-pin','Location Pin'],
['solid/location-pin-lock','Location Pin Lock'],
['solid/lock','Lock'],
['solid/lock-open','Lock Open'],
['solid/locust','Locust'],
['brands/lumon','Lumon'],
['brands/lumon-drop','Lumon Drop'],
['solid/lungs','Lungs'],
['solid/lungs-virus','Lungs Virus'],
['brands/lyft','Lyft'],
['solid/m','M'],
['brands/magento','Magento'],
['solid/magnet','Magnet'],
['solid/magnifying-glass','Magnifying Glass'],
['solid/magnifying-glass-arrow-right','Magnifying Glass Arrow Right'],
['solid/magnifying-glass-chart','Magnifying Glass Chart'],
['solid/magnifying-glass-dollar','Magnifying Glass Dollar'],
['solid/magnifying-glass-location','Magnifying Glass Location'],
['solid/magnifying-glass-minus','Magnifying Glass Minus'],
['solid/magnifying-glass-plus','Magnifying Glass Plus'],
['brands/mailchimp','Mailchimp'],
['solid/manat-sign','Manat Sign'],
['brands/mandalorian','Mandalorian'],
['regular/map','Map'],
['solid/map','Map'],
['solid/map-location','Map Location'],
['solid/map-location-dot','Map Location Dot'],
['solid/map-pin','Map Pin'],
['brands/markdown','Markdown'],
['solid/marker','Marker'],
['solid/mars','Mars'],
['solid/mars-and-venus','Mars And Venus'],
['solid/mars-and-venus-burst','Mars And Venus Burst'],
['solid/mars-double','Mars Double'],
['solid/mars-stroke','Mars Stroke'],
['solid/mars-stroke-right','Mars Stroke Right'],
['solid/mars-stroke-up','Mars Stroke Up'],
['solid/martini-glass','Martini Glass'],
['solid/martini-glass-citrus','Martini Glass Citrus'],
['solid/martini-glass-empty','Martini Glass Empty'],
['solid/mask','Mask'],
['solid/mask-face','Mask Face'],
['solid/mask-ventilator','Mask Ventilator'],
['solid/masks-theater','Masks Theater'],
['brands/mastodon','Mastodon'],
['brands/matrix','Matrix'],
['brands/mattermost','Mattermost'],
['solid/mattress-pillow','Mattress Pillow'],
['brands/maxcdn','Maxcdn'],
['solid/maximize','Maximize'],
['brands/mdb','Mdb'],
['solid/medal','Medal'],
['brands/medapps','Medapps'],
['brands/medium','Medium'],
['brands/medrt','Medrt'],
['brands/meetup','Meetup'],
['brands/megaport','Megaport'],
['solid/memory','Memory'],
['brands/mendeley','Mendeley'],
['solid/menorah','Menorah'],
['solid/mercury','Mercury'],
['regular/message','Message'],
['solid/message','Message'],
['brands/meta','Meta'],
['solid/meteor','Meteor'],
['brands/microblog','Microblog'],
['solid/microchip','Microchip'],
['solid/microphone','Microphone'],
['solid/microphone-lines','Microphone Lines'],
['solid/microphone-lines-slash','Microphone Lines Slash'],
['solid/microphone-slash','Microphone Slash'],
['solid/microscope','Microscope'],
['brands/microsoft','Microsoft'],
['solid/mill-sign','Mill Sign'],
['solid/minimize','Minimize'],
['brands/mintbit','Mintbit'],
['solid/minus','Minus'],
['solid/mitten','Mitten'],
['brands/mix','Mix'],
['brands/mixcloud','Mixcloud'],
['brands/mixer','Mixer'],
['brands/mizuni','Mizuni'],
['solid/mobile','Mobile'],
['solid/mobile-button','Mobile Button'],
['solid/mobile-retro','Mobile Retro'],
['solid/mobile-screen','Mobile Screen'],
['solid/mobile-screen-button','Mobile Screen Button'],
['solid/mobile-vibrate','Mobile Vibrate'],
['brands/modx','Modx'],
['brands/monero','Monero'],
['solid/money-bill','Money Bill'],
['regular/money-bill-1','Money Bill 1'],
['solid/money-bill-1','Money Bill 1'],
['solid/money-bill-1-wave','Money Bill 1 Wave'],
['solid/money-bill-transfer','Money Bill Transfer'],
['solid/money-bill-trend-up','Money Bill Trend Up'],
['solid/money-bill-wave','Money Bill Wave'],
['solid/money-bill-wheat','Money Bill Wheat'],
['solid/money-bills','Money Bills'],
['solid/money-check','Money Check'],
['solid/money-check-dollar','Money Check Dollar'],
['solid/monument','Monument'],
['regular/moon','Moon'],
['solid/moon','Moon'],
['solid/mortar-pestle','Mortar Pestle'],
['solid/mosque','Mosque'],
['solid/mosquito','Mosquito'],
['solid/mosquito-net','Mosquito Net'],
['solid/motorcycle','Motorcycle'],
['solid/mound','Mound'],
['solid/mountain','Mountain'],
['solid/mountain-city','Mountain City'],
['solid/mountain-sun','Mountain Sun'],
['solid/mug-hot','Mug Hot'],
['solid/mug-saucer','Mug Saucer'],
['solid/music','Music'],
['solid/n','N'],
['solid/naira-sign','Naira Sign'],
['brands/napster','Napster'],
['brands/neos','Neos'],
['solid/network-wired','Network Wired'],
['solid/neuter','Neuter'],
['regular/newspaper','Newspaper'],
['solid/newspaper','Newspaper'],
['brands/nextcloud','Nextcloud'],
['brands/nfc-directional','Nfc Directional'],
['brands/nfc-symbol','Nfc Symbol'],
['brands/nimblr','Nimblr'],
['brands/node','Node'],
['brands/node-js','Node Js'],
['solid/non-binary','Non Binary'],
['solid/not-equal','Not Equal'],
['solid/notdef','Notdef'],
['regular/note-sticky','Note Sticky'],
['solid/note-sticky','Note Sticky'],
['solid/notes-medical','Notes Medical'],
['brands/notion','Notion'],
['brands/npm','Npm'],
['brands/ns8','Ns8'],
['brands/nutritionix','Nutritionix'],
['solid/o','O'],
['regular/object-group','Object Group'],
['solid/object-group','Object Group'],
['regular/object-ungroup','Object Ungroup'],
['solid/object-ungroup','Object Ungroup'],
['brands/obs-studio','Obs Studio'],
['brands/obsidian','Obsidian'],
['solid/octagon','Octagon'],
['brands/octopus-deploy','Octopus Deploy'],
['brands/odnoklassniki','Odnoklassniki'],
['brands/odysee','Odysee'],
['solid/oil-can','Oil Can'],
['solid/oil-well','Oil Well'],
['brands/old-republic','Old Republic'],
['solid/om','Om'],
['brands/openai','Openai'],
['brands/opencart','Opencart'],
['brands/openid','Openid'],
['brands/openstreetmap','Openstreetmap'],
['brands/opensuse','Opensuse'],
['brands/opera','Opera'],
['brands/optin-monster','Optin Monster'],
['brands/orcid','Orcid'],
['brands/osi','Osi'],
['solid/otter','Otter'],
['solid/outdent','Outdent'],
['solid/p','P'],
['brands/padlet','Padlet'],
['brands/page4','Page4'],
['brands/pagelines','Pagelines'],
['solid/pager','Pager'],
['solid/paint-roller','Paint Roller'],
['solid/paintbrush','Paintbrush'],
['solid/palette','Palette'],
['brands/palfed','Palfed'],
['solid/pallet','Pallet'],
['brands/pandora','Pandora'],
['solid/panorama','Panorama'],
['regular/paper-plane','Paper Plane'],
['solid/paper-plane','Paper Plane'],
['solid/paperclip','Paperclip'],
['solid/parachute-box','Parachute Box'],
['solid/paragraph','Paragraph'],
['solid/passport','Passport'],
['regular/paste','Paste'],
['solid/paste','Paste'],
['brands/patreon','Patreon'],
['solid/pause','Pause'],
['solid/paw','Paw'],
['brands/paypal','Paypal'],
['solid/peace','Peace'],
['solid/pen','Pen'],
['solid/pen-clip','Pen Clip'],
['solid/pen-fancy','Pen Fancy'],
['solid/pen-nib','Pen Nib'],
['solid/pen-ruler','Pen Ruler'],
['regular/pen-to-square','Pen To Square'],
['solid/pen-to-square','Pen To Square'],
['solid/pencil','Pencil'],
['solid/pentagon','Pentagon'],
['solid/people-arrows','People Arrows'],
['solid/people-carry-box','People Carry Box'],
['solid/people-group','People Group'],
['solid/people-line','People Line'],
['solid/people-pulling','People Pulling'],
['solid/people-robbery','People Robbery'],
['solid/people-roof','People Roof'],
['solid/pepper-hot','Pepper Hot'],
['brands/perbyte','Perbyte'],
['solid/percent','Percent'],
['brands/periscope','Periscope'],
['solid/person','Person'],
['solid/person-arrow-down-to-line','Person Arrow Down To Line'],
['solid/person-arrow-up-from-line','Person Arrow Up From Line'],
['solid/person-biking','Person Biking'],
['solid/person-booth','Person Booth'],
['solid/person-breastfeeding','Person Breastfeeding'],
['solid/person-burst','Person Burst'],
['solid/person-cane','Person Cane'],
['solid/person-chalkboard','Person Chalkboard'],
['solid/person-circle-check','Person Circle Check'],
['solid/person-circle-exclamation','Person Circle Exclamation'],
['solid/person-circle-minus','Person Circle Minus'],
['solid/person-circle-plus','Person Circle Plus'],
['solid/person-circle-question','Person Circle Question'],
['solid/person-circle-xmark','Person Circle Xmark'],
['solid/person-digging','Person Digging'],
['solid/person-dots-from-line','Person Dots From Line'],
['solid/person-dress','Person Dress'],
['solid/person-dress-burst','Person Dress Burst'],
['solid/person-drowning','Person Drowning'],
['solid/person-falling','Person Falling'],
['solid/person-falling-burst','Person Falling Burst'],
['solid/person-half-dress','Person Half Dress'],
['solid/person-harassing','Person Harassing'],
['solid/person-hiking','Person Hiking'],
['solid/person-military-pointing','Person Military Pointing'],
['solid/person-military-rifle','Person Military Rifle'],
['solid/person-military-to-person','Person Military To Person'],
['solid/person-praying','Person Praying'],
['solid/person-pregnant','Person Pregnant'],
['solid/person-rays','Person Rays'],
['solid/person-rifle','Person Rifle'],
['solid/person-running','Person Running'],
['solid/person-shelter','Person Shelter'],
['solid/person-skating','Person Skating'],
['solid/person-skiing','Person Skiing'],
['solid/person-skiing-nordic','Person Skiing Nordic'],
['solid/person-snowboarding','Person Snowboarding'],
['solid/person-swimming','Person Swimming'],
['solid/person-through-window','Person Through Window'],
['solid/person-walking','Person Walking'],
['solid/person-walking-arrow-loop-left','Person Walking Arrow Loop Left'],
['solid/person-walking-arrow-right','Person Walking Arrow Right'],
['solid/person-walking-dashed-line-arrow-right','Person Walking Dashed Line Arrow Right'],
['solid/person-walking-luggage','Person Walking Luggage'],
['solid/person-walking-with-cane','Person Walking With Cane'],
['solid/peseta-sign','Peseta Sign'],
['solid/peso-sign','Peso Sign'],
['brands/phabricator','Phabricator'],
['brands/phoenix-framework','Phoenix Framework'],
['brands/phoenix-squadron','Phoenix Squadron'],
['solid/phone','Phone'],
['solid/phone-flip','Phone Flip'],
['solid/phone-slash','Phone Slash'],
['solid/phone-volume','Phone Volume'],
['solid/photo-film','Photo Film'],
['brands/php','Php'],
['solid/picture-in-picture','Picture In Picture'],
['brands/pied-piper','Pied Piper'],
['brands/pied-piper-alt','Pied Piper Alt'],
['brands/pied-piper-hat','Pied Piper Hat'],
['brands/pied-piper-pp','Pied Piper Pp'],
['solid/piggy-bank','Piggy Bank'],
['solid/pills','Pills'],
['brands/pinterest','Pinterest'],
['brands/pinterest-p','Pinterest P'],
['solid/pisces','Pisces'],
['brands/pix','Pix'],
['brands/pixelfed','Pixelfed'],
['brands/pixiv','Pixiv'],
['solid/pizza-slice','Pizza Slice'],
['solid/place-of-worship','Place Of Worship'],
['solid/plane','Plane'],
['solid/plane-arrival','Plane Arrival'],
['solid/plane-circle-check','Plane Circle Check'],
['solid/plane-circle-exclamation','Plane Circle Exclamation'],
['solid/plane-circle-xmark','Plane Circle Xmark'],
['solid/plane-departure','Plane Departure'],
['solid/plane-lock','Plane Lock'],
['solid/plane-slash','Plane Slash'],
['solid/plane-up','Plane Up'],
['solid/plant-wilt','Plant Wilt'],
['solid/plate-wheat','Plate Wheat'],
['solid/play','Play'],
['brands/playstation','Playstation'],
['solid/plug','Plug'],
['solid/plug-circle-bolt','Plug Circle Bolt'],
['solid/plug-circle-check','Plug Circle Check'],
['solid/plug-circle-exclamation','Plug Circle Exclamation'],
['solid/plug-circle-minus','Plug Circle Minus'],
['solid/plug-circle-plus','Plug Circle Plus'],
['solid/plug-circle-xmark','Plug Circle Xmark'],
['solid/plus','Plus'],
['solid/plus-minus','Plus Minus'],
['solid/podcast','Podcast'],
['solid/poo','Poo'],
['solid/poo-storm','Poo Storm'],
['solid/poop','Poop'],
['brands/postgresql','Postgresql'],
['solid/power-off','Power Off'],
['solid/prescription','Prescription'],
['solid/prescription-bottle','Prescription Bottle'],
['solid/prescription-bottle-medical','Prescription Bottle Medical'],
['solid/print','Print'],
['brands/product-hunt','Product Hunt'],
['solid/pump-medical','Pump Medical'],
['solid/pump-soap','Pump Soap'],
['brands/pushed','Pushed'],
['solid/puzzle-piece','Puzzle Piece'],
['brands/python','Python'],
['solid/q','Q'],
['brands/qq','Qq'],
['solid/qrcode','Qrcode'],
['solid/question','Question'],
['brands/quinscape','Quinscape'],
['brands/quora','Quora'],
['solid/quote-left','Quote Left'],
['solid/quote-right','Quote Right'],
['solid/r','R'],
['brands/r-project','R Project'],
['solid/radiation','Radiation'],
['solid/radio','Radio'],
['solid/rainbow','Rainbow'],
['solid/ranking-star','Ranking Star'],
['brands/raspberry-pi','Raspberry Pi'],
['brands/ravelry','Ravelry'],
['brands/react','React'],
['brands/reacteurope','Reacteurope'],
['brands/readme','Readme'],
['brands/rebel','Rebel'],
['solid/receipt','Receipt'],
['solid/record-vinyl','Record Vinyl'],
['solid/rectangle-ad','Rectangle Ad'],
['regular/rectangle-list','Rectangle List'],
['solid/rectangle-list','Rectangle List'],
['regular/rectangle-xmark','Rectangle Xmark'],
['solid/rectangle-xmark','Rectangle Xmark'],
['solid/recycle','Recycle'],
['brands/red-river','Red River'],
['brands/reddit','Reddit'],
['brands/reddit-alien','Reddit Alien'],
['brands/redhat','Redhat'],
['regular/registered','Registered'],
['solid/registered','Registered'],
['brands/renren','Renren'],
['solid/repeat','Repeat'],
['solid/reply','Reply'],
['solid/reply-all','Reply All'],
['brands/replyd','Replyd'],
['solid/republican','Republican'],
['brands/researchgate','Researchgate'],
['brands/resolving','Resolving'],
['solid/restroom','Restroom'],
['solid/retweet','Retweet'],
['brands/rev','Rev'],
['solid/ribbon','Ribbon'],
['solid/right-from-bracket','Right From Bracket'],
['solid/right-left','Right Left'],
['solid/right-long','Right Long'],
['solid/right-to-bracket','Right To Bracket'],
['solid/ring','Ring'],
['solid/road','Road'],
['solid/road-barrier','Road Barrier'],
['solid/road-bridge','Road Bridge'],
['solid/road-circle-check','Road Circle Check'],
['solid/road-circle-exclamation','Road Circle Exclamation'],
['solid/road-circle-xmark','Road Circle Xmark'],
['solid/road-lock','Road Lock'],
['solid/road-spikes','Road Spikes'],
['brands/roblox-creator-studio','Roblox Creator Studio'],
['solid/robot','Robot'],
['solid/rocket','Rocket'],
['brands/rocketchat','Rocketchat'],
['brands/rockrms','Rockrms'],
['brands/ror','Ror'],
['solid/rotate','Rotate'],
['solid/rotate-left','Rotate Left'],
['solid/rotate-right','Rotate Right'],
['solid/route','Route'],
['solid/rss','Rss'],
['solid/ruble-sign','Ruble Sign'],
['solid/rug','Rug'],
['solid/ruler','Ruler'],
['solid/ruler-combined','Ruler Combined'],
['solid/ruler-horizontal','Ruler Horizontal'],
['solid/ruler-vertical','Ruler Vertical'],
['solid/rupee-sign','Rupee Sign'],
['solid/rupiah-sign','Rupiah Sign'],
['brands/rust','Rust'],
['solid/s','S'],
['solid/sack-dollar','Sack Dollar'],
['solid/sack-xmark','Sack Xmark'],
['brands/safari','Safari'],
['solid/sagittarius','Sagittarius'],
['solid/sailboat','Sailboat'],
['brands/salesforce','Salesforce'],
['brands/sass','Sass'],
['solid/satellite','Satellite'],
['solid/satellite-dish','Satellite Dish'],
['solid/scale-balanced','Scale Balanced'],
['solid/scale-unbalanced','Scale Unbalanced'],
['solid/scale-unbalanced-flip','Scale Unbalanced Flip'],
['brands/scaleway','Scaleway'],
['brands/schlix','Schlix'],
['solid/school','School'],
['solid/school-circle-check','School Circle Check'],
['solid/school-circle-exclamation','School Circle Exclamation'],
['solid/school-circle-xmark','School Circle Xmark'],
['solid/school-flag','School Flag'],
['solid/school-lock','School Lock'],
['solid/scissors','Scissors'],
['solid/scorpio','Scorpio'],
['brands/screenpal','Screenpal'],
['solid/screwdriver','Screwdriver'],
['solid/screwdriver-wrench','Screwdriver Wrench'],
['brands/scribd','Scribd'],
['solid/scroll','Scroll'],
['solid/scroll-torah','Scroll Torah'],
['solid/sd-card','Sd Card'],
['brands/searchengin','Searchengin'],
['solid/section','Section'],
['solid/seedling','Seedling'],
['brands/sellcast','Sellcast'],
['brands/sellsy','Sellsy'],
['solid/septagon','Septagon'],
['solid/server','Server'],
['brands/servicestack','Servicestack'],
['solid/shapes','Shapes'],
['solid/share','Share'],
['regular/share-from-square','Share From Square'],
['solid/share-from-square','Share From Square'],
['solid/share-nodes','Share Nodes'],
['solid/sheet-plastic','Sheet Plastic'],
['solid/shekel-sign','Shekel Sign'],
['solid/shield','Shield'],
['solid/shield-cat','Shield Cat'],
['solid/shield-dog','Shield Dog'],
['solid/shield-halved','Shield Halved'],
['solid/shield-heart','Shield Heart'],
['solid/shield-virus','Shield Virus'],
['solid/ship','Ship'],
['solid/shirt','Shirt'],
['brands/shirtsinbulk','Shirtsinbulk'],
['solid/shoe-prints','Shoe Prints'],
['brands/shoelace','Shoelace'],
['solid/shop','Shop'],
['solid/shop-lock','Shop Lock'],
['solid/shop-slash','Shop Slash'],
['brands/shopify','Shopify'],
['brands/shopware','Shopware'],
['solid/shower','Shower'],
['solid/shrimp','Shrimp'],
['solid/shuffle','Shuffle'],
['solid/shuttle-space','Shuttle Space'],
['solid/sign-hanging','Sign Hanging'],
['solid/signal','Signal'],
['brands/signal-messenger','Signal Messenger'],
['solid/signature','Signature'],
['solid/signs-post','Signs Post'],
['solid/sim-card','Sim Card'],
['brands/simplybuilt','Simplybuilt'],
['solid/single-quote-left','Single Quote Left'],
['solid/single-quote-right','Single Quote Right'],
['solid/sink','Sink'],
['brands/sistrix','Sistrix'],
['solid/sitemap','Sitemap'],
['brands/sith','Sith'],
['brands/sitrox','Sitrox'],
['brands/sketch','Sketch'],
['solid/skull','Skull'],
['solid/skull-crossbones','Skull Crossbones'],
['brands/skyatlas','Skyatlas'],
['brands/skype','Skype'],
['brands/slack','Slack'],
['solid/slash','Slash'],
['solid/sleigh','Sleigh'],
['solid/sliders','Sliders'],
['brands/slideshare','Slideshare'],
['solid/smog','Smog'],
['solid/smoking','Smoking'],
['brands/snapchat','Snapchat'],
['regular/snowflake','Snowflake'],
['solid/snowflake','Snowflake'],
['solid/snowman','Snowman'],
['solid/snowplow','Snowplow'],
['solid/soap','Soap'],
['solid/socks','Socks'],
['brands/solana','Solana'],
['solid/solar-panel','Solar Panel'],
['solid/sort','Sort'],
['solid/sort-down','Sort Down'],
['solid/sort-up','Sort Up'],
['brands/soundcloud','Soundcloud'],
['brands/sourcetree','Sourcetree'],
['solid/spa','Spa'],
['brands/space-awesome','Space Awesome'],
['solid/spaghetti-monster-flying','Spaghetti Monster Flying'],
['brands/speakap','Speakap'],
['brands/speaker-deck','Speaker Deck'],
['solid/spell-check','Spell Check'],
['solid/spider','Spider'],
['solid/spinner','Spinner'],
['solid/spiral','Spiral'],
['solid/splotch','Splotch'],
['solid/spoon','Spoon'],
['brands/spotify','Spotify'],
['solid/spray-can','Spray Can'],
['solid/spray-can-sparkles','Spray Can Sparkles'],
['regular/square','Square'],
['solid/square','Square'],
['solid/square-arrow-up-right','Square Arrow Up Right'],
['brands/square-behance','Square Behance'],
['solid/square-binary','Square Binary'],
['brands/square-bluesky','Square Bluesky'],
['brands/square-build-awesome-stroke','Square Build Awesome Stroke'],
['regular/square-caret-down','Square Caret Down'],
['solid/square-caret-down','Square Caret Down'],
['regular/square-caret-left','Square Caret Left'],
['solid/square-caret-left','Square Caret Left'],
['regular/square-caret-right','Square Caret Right'],
['solid/square-caret-right','Square Caret Right'],
['regular/square-caret-up','Square Caret Up'],
['solid/square-caret-up','Square Caret Up'],
['regular/square-check','Square Check'],
['solid/square-check','Square Check'],
['brands/square-deskpro','Square Deskpro'],
['brands/square-dribbble','Square Dribbble'],
['solid/square-envelope','Square Envelope'],
['brands/square-facebook','Square Facebook'],
['brands/square-figma','Square Figma'],
['brands/square-font-awesome','Square Font Awesome'],
['brands/square-font-awesome-stroke','Square Font Awesome Stroke'],
['regular/square-full','Square Full'],
['solid/square-full','Square Full'],
['brands/square-git','Square Git'],
['brands/square-github','Square Github'],
['brands/square-gitlab','Square Gitlab'],
['brands/square-google-plus','Square Google Plus'],
['solid/square-h','Square H'],
['brands/square-hacker-news','Square Hacker News'],
['brands/square-instagram','Square Instagram'],
['brands/square-js','Square Js'],
['brands/square-lastfm','Square Lastfm'],
['brands/square-letterboxd','Square Letterboxd'],
['brands/square-linkedin','Square Linkedin'],
['regular/square-minus','Square Minus'],
['solid/square-minus','Square Minus'],
['solid/square-nfi','Square Nfi'],
['brands/square-odnoklassniki','Square Odnoklassniki'],
['solid/square-parking','Square Parking'],
['solid/square-pen','Square Pen'],
['solid/square-person-confined','Square Person Confined'],
['solid/square-phone','Square Phone'],
['solid/square-phone-flip','Square Phone Flip'],
['brands/square-pied-piper','Square Pied Piper'],
['brands/square-pinterest','Square Pinterest'],
['regular/square-plus','Square Plus'],
['solid/square-plus','Square Plus'],
['solid/square-poll-horizontal','Square Poll Horizontal'],
['solid/square-poll-vertical','Square Poll Vertical'],
['brands/square-reddit','Square Reddit'],
['solid/square-root-variable','Square Root Variable'],
['solid/square-rss','Square Rss'],
['solid/square-share-nodes','Square Share Nodes'],
['brands/square-snapchat','Square Snapchat'],
['brands/square-steam','Square Steam'],
['brands/square-threads','Square Threads'],
['brands/square-tumblr','Square Tumblr'],
['brands/square-twitter','Square Twitter'],
['solid/square-up-right','Square Up Right'],
['brands/square-upwork','Square Upwork'],
['brands/square-viadeo','Square Viadeo'],
['brands/square-vimeo','Square Vimeo'],
['solid/square-virus','Square Virus'],
['brands/square-web-awesome','Square Web Awesome'],
['brands/square-web-awesome-stroke','Square Web Awesome Stroke'],
['brands/square-whatsapp','Square Whatsapp'],
['brands/square-x-twitter','Square X Twitter'],
['brands/square-xing','Square Xing'],
['solid/square-xmark','Square Xmark'],
['brands/square-youtube','Square Youtube'],
['brands/squarespace','Squarespace'],
['brands/stack-exchange','Stack Exchange'],
['brands/stack-overflow','Stack Overflow'],
['brands/stackpath','Stackpath'],
['solid/staff-snake','Staff Snake'],
['solid/stairs','Stairs'],
['solid/stamp','Stamp'],
['solid/stapler','Stapler'],
['regular/star','Star'],
['solid/star','Star'],
['solid/star-and-crescent','Star And Crescent'],
['regular/star-half','Star Half'],
['solid/star-half','Star Half'],
['regular/star-half-stroke','Star Half Stroke'],
['solid/star-half-stroke','Star Half Stroke'],
['solid/star-of-david','Star Of David'],
['solid/star-of-life','Star Of Life'],
['brands/staylinked','Staylinked'],
['brands/steam','Steam'],
['brands/steam-symbol','Steam Symbol'],
['solid/sterling-sign','Sterling Sign'],
['solid/stethoscope','Stethoscope'],
['brands/sticker-mule','Sticker Mule'],
['solid/stop','Stop'],
['solid/stopwatch','Stopwatch'],
['solid/stopwatch-20','Stopwatch 20'],
['solid/store','Store'],
['solid/store-slash','Store Slash'],
['brands/storybook','Storybook'],
['brands/strava','Strava'],
['solid/street-view','Street View'],
['solid/strikethrough','Strikethrough'],
['brands/stripe','Stripe'],
['brands/stripe-s','Stripe S'],
['solid/stroopwafel','Stroopwafel'],
['brands/stubber','Stubber'],
['brands/studiovinari','Studiovinari'],
['brands/stumbleupon','Stumbleupon'],
['brands/stumbleupon-circle','Stumbleupon Circle'],
['solid/subscript','Subscript'],
['brands/substack','Substack'],
['solid/suitcase','Suitcase'],
['solid/suitcase-medical','Suitcase Medical'],
['solid/suitcase-rolling','Suitcase Rolling'],
['regular/sun','Sun'],
['solid/sun','Sun'],
['solid/sun-plant-wilt','Sun Plant Wilt'],
['brands/superpowers','Superpowers'],
['solid/superscript','Superscript'],
['brands/supple','Supple'],
['brands/supportnow','Supportnow'],
['brands/suse','Suse'],
['brands/svelte','Svelte'],
['solid/swatchbook','Swatchbook'],
['brands/swift','Swift'],
['brands/symfony','Symfony'],
['brands/symfonycasts','Symfonycasts'],
['solid/synagogue','Synagogue'],
['solid/syringe','Syringe'],
['solid/t','T'],
['solid/table','Table'],
['solid/table-cells','Table Cells'],
['solid/table-cells-column-lock','Table Cells Column Lock'],
['solid/table-cells-large','Table Cells Large'],
['solid/table-cells-row-lock','Table Cells Row Lock'],
['solid/table-cells-row-unlock','Table Cells Row Unlock'],
['solid/table-columns','Table Columns'],
['solid/table-list','Table List'],
['solid/table-tennis-paddle-ball','Table Tennis Paddle Ball'],
['solid/tablet','Tablet'],
['solid/tablet-button','Tablet Button'],
['solid/tablet-screen-button','Tablet Screen Button'],
['solid/tablets','Tablets'],
['solid/tachograph-digital','Tachograph Digital'],
['solid/tag','Tag'],
['solid/tags','Tags'],
['brands/tailwind-css','Tailwind Css'],
['solid/tape','Tape'],
['solid/tarp','Tarp'],
['solid/tarp-droplet','Tarp Droplet'],
['solid/taurus','Taurus'],
['solid/taxi','Taxi'],
['brands/teamspeak','Teamspeak'],
['solid/teeth','Teeth'],
['solid/teeth-open','Teeth Open'],
['brands/telegram','Telegram'],
['solid/temperature-arrow-down','Temperature Arrow Down'],
['solid/temperature-arrow-up','Temperature Arrow Up'],
['solid/temperature-empty','Temperature Empty'],
['solid/temperature-full','Temperature Full'],
['solid/temperature-half','Temperature Half'],
['solid/temperature-high','Temperature High'],
['solid/temperature-low','Temperature Low'],
['solid/temperature-quarter','Temperature Quarter'],
['solid/temperature-three-quarters','Temperature Three Quarters'],
['brands/tencent-weibo','Tencent Weibo'],
['solid/tenge-sign','Tenge Sign'],
['solid/tent','Tent'],
['solid/tent-arrow-down-to-line','Tent Arrow Down To Line'],
['solid/tent-arrow-left-right','Tent Arrow Left Right'],
['solid/tent-arrow-turn-left','Tent Arrow Turn Left'],
['solid/tent-arrows-down','Tent Arrows Down'],
['solid/tents','Tents'],
['solid/terminal','Terminal'],
['brands/tesla','Tesla'],
['brands/tex','Tex'],
['solid/text-height','Text Height'],
['solid/text-slash','Text Slash'],
['solid/text-width','Text Width'],
['brands/the-red-yeti','The Red Yeti'],
['brands/themeco','Themeco'],
['brands/themeisle','Themeisle'],
['solid/thermometer','Thermometer'],
['brands/think-peaks','Think Peaks'],
['brands/threads','Threads'],
['brands/threema','Threema'],
['regular/thumbs-down','Thumbs Down'],
['solid/thumbs-down','Thumbs Down'],
['regular/thumbs-up','Thumbs Up'],
['solid/thumbs-up','Thumbs Up'],
['solid/thumbtack','Thumbtack'],
['solid/thumbtack-slash','Thumbtack Slash'],
['solid/ticket','Ticket'],
['solid/ticket-simple','Ticket Simple'],
['brands/tidal','Tidal'],
['brands/tiktok','Tiktok'],
['solid/timeline','Timeline'],
['solid/toggle-off','Toggle Off'],
['solid/toggle-on','Toggle On'],
['solid/toilet','Toilet'],
['solid/toilet-paper','Toilet Paper'],
['solid/toilet-paper-slash','Toilet Paper Slash'],
['solid/toilet-portable','Toilet Portable'],
['solid/toilets-portable','Toilets Portable'],
['solid/toolbox','Toolbox'],
['solid/tooth','Tooth'],
['brands/tor-browser','Tor Browser'],
['solid/torii-gate','Torii Gate'],
['solid/tornado','Tornado'],
['solid/tower-broadcast','Tower Broadcast'],
['solid/tower-cell','Tower Cell'],
['solid/tower-observation','Tower Observation'],
['solid/tractor','Tractor'],
['brands/trade-federation','Trade Federation'],
['solid/trademark','Trademark'],
['solid/traffic-light','Traffic Light'],
['solid/trailer','Trailer'],
['solid/train','Train'],
['solid/train-subway','Train Subway'],
['solid/train-tram','Train Tram'],
['solid/transgender','Transgender'],
['solid/trash','Trash'],
['solid/trash-arrow-up','Trash Arrow Up'],
['regular/trash-can','Trash Can'],
['solid/trash-can','Trash Can'],
['solid/trash-can-arrow-up','Trash Can Arrow Up'],
['solid/tree','Tree'],
['solid/tree-city','Tree City'],
['brands/trello','Trello'],
['solid/triangle-exclamation','Triangle Exclamation'],
['solid/trophy','Trophy'],
['solid/trowel','Trowel'],
['solid/trowel-bricks','Trowel Bricks'],
['regular/truck','Truck'],
['solid/truck','Truck'],
['solid/truck-arrow-right','Truck Arrow Right'],
['solid/truck-droplet','Truck Droplet'],
['solid/truck-fast','Truck Fast'],
['solid/truck-field','Truck Field'],
['solid/truck-field-un','Truck Field Un'],
['solid/truck-front','Truck Front'],
['solid/truck-medical','Truck Medical'],
['solid/truck-monster','Truck Monster'],
['solid/truck-moving','Truck Moving'],
['solid/truck-pickup','Truck Pickup'],
['solid/truck-plane','Truck Plane'],
['solid/truck-ramp-box','Truck Ramp Box'],
['solid/tty','Tty'],
['brands/tumblr','Tumblr'],
['solid/turkish-lira-sign','Turkish Lira Sign'],
['solid/turn-down','Turn Down'],
['solid/turn-up','Turn Up'],
['solid/tv','Tv'],
['brands/twitch','Twitch'],
['brands/twitter','Twitter'],
['brands/typescript','Typescript'],
['brands/typo3','Typo3'],
['solid/u','U'],
['brands/uber','Uber'],
['brands/ubuntu','Ubuntu'],
['brands/uikit','Uikit'],
['brands/ultralytics','Ultralytics'],
['brands/ultralytics-hub','Ultralytics Hub'],
['brands/ultralytics-yolo','Ultralytics Yolo'],
['brands/umbraco','Umbraco'],
['solid/umbrella','Umbrella'],
['solid/umbrella-beach','Umbrella Beach'],
['brands/uncharted','Uncharted'],
['solid/underline','Underline'],
['brands/uniregistry','Uniregistry'],
['brands/unison','Unison'],
['brands/unity','Unity'],
['solid/universal-access','Universal Access'],
['solid/unlock','Unlock'],
['solid/unlock-keyhole','Unlock Keyhole'],
['brands/unreal-engine','Unreal Engine'],
['brands/unsplash','Unsplash'],
['brands/untappd','Untappd'],
['solid/up-down','Up Down'],
['solid/up-down-left-right','Up Down Left Right'],
['solid/up-long','Up Long'],
['solid/up-right-and-down-left-from-center','Up Right And Down Left From Center'],
['solid/up-right-from-square','Up Right From Square'],
['solid/upload','Upload'],
['brands/ups','Ups'],
['brands/upwork','Upwork'],
['brands/usb','Usb'],
['regular/user','User'],
['solid/user','User'],
['solid/user-astronaut','User Astronaut'],
['solid/user-check','User Check'],
['solid/user-clock','User Clock'],
['solid/user-doctor','User Doctor'],
['solid/user-gear','User Gear'],
['solid/user-graduate','User Graduate'],
['solid/user-group','User Group'],
['solid/user-injured','User Injured'],
['solid/user-lock','User Lock'],
['solid/user-minus','User Minus'],
['solid/user-ninja','User Ninja'],
['solid/user-nurse','User Nurse'],
['solid/user-pen','User Pen'],
['solid/user-plus','User Plus'],
['solid/user-secret','User Secret'],
['solid/user-shield','User Shield'],
['solid/user-slash','User Slash'],
['solid/user-tag','User Tag'],
['solid/user-tie','User Tie'],
['solid/user-xmark','User Xmark'],
['solid/users','Users'],
['solid/users-between-lines','Users Between Lines'],
['solid/users-gear','Users Gear'],
['solid/users-line','Users Line'],
['solid/users-rays','Users Rays'],
['solid/users-rectangle','Users Rectangle'],
['solid/users-slash','Users Slash'],
['solid/users-viewfinder','Users Viewfinder'],
['brands/usps','Usps'],
['brands/ussunnah','Ussunnah'],
['solid/utensils','Utensils'],
['solid/v','V'],
['brands/vaadin','Vaadin'],
['solid/van-shuttle','Van Shuttle'],
['solid/vault','Vault'],
['brands/venmo','Venmo'],
['brands/venmo-v','Venmo V'],
['solid/venus','Venus'],
['solid/venus-double','Venus Double'],
['solid/venus-mars','Venus Mars'],
['solid/vest','Vest'],
['solid/vest-patches','Vest Patches'],
['brands/viacoin','Viacoin'],
['brands/viadeo','Viadeo'],
['solid/vial','Vial'],
['solid/vial-circle-check','Vial Circle Check'],
['solid/vial-virus','Vial Virus'],
['solid/vials','Vials'],
['brands/viber','Viber'],
['solid/video','Video'],
['solid/video-slash','Video Slash'],
['solid/vihara','Vihara'],
['brands/vim','Vim'],
['brands/vimeo','Vimeo'],
['brands/vimeo-v','Vimeo V'],
['brands/vine','Vine'],
['solid/virgo','Virgo'],
['solid/virus','Virus'],
['solid/virus-covid','Virus Covid'],
['solid/virus-covid-slash','Virus Covid Slash'],
['solid/virus-slash','Virus Slash'],
['solid/viruses','Viruses'],
['brands/visual-studio','Visual Studio'],
['brands/vk','Vk'],
['brands/vnv','Vnv'],
['solid/voicemail','Voicemail'],
['solid/volcano','Volcano'],
['solid/volleyball','Volleyball'],
['solid/volume','Volume'],
['solid/volume-high','Volume High'],
['solid/volume-low','Volume Low'],
['solid/volume-off','Volume Off'],
['solid/volume-xmark','Volume Xmark'],
['solid/vr-cardboard','Vr Cardboard'],
['brands/vsco','Vsco'],
['brands/vuejs','Vuejs'],
['solid/w','W'],
['brands/w3c','W3c'],
['solid/walkie-talkie','Walkie Talkie'],
['solid/wallet','Wallet'],
['solid/wand-magic','Wand Magic'],
['solid/wand-magic-sparkles','Wand Magic Sparkles'],
['solid/wand-sparkles','Wand Sparkles'],
['solid/warehouse','Warehouse'],
['brands/watchman-monitoring','Watchman Monitoring'],
['solid/water','Water'],
['solid/water-ladder','Water Ladder'],
['solid/wave-square','Wave Square'],
['brands/waze','Waze'],
['brands/web-awesome','Web Awesome'],
['solid/web-awesome','Web Awesome'],
['brands/webflow','Webflow'],
['brands/weebly','Weebly'],
['brands/weibo','Weibo'],
['solid/weight-hanging','Weight Hanging'],
['solid/weight-scale','Weight Scale'],
['brands/weixin','Weixin'],
['brands/whatsapp','Whatsapp'],
['solid/wheat-awn','Wheat Awn'],
['solid/wheat-awn-circle-exclamation','Wheat Awn Circle Exclamation'],
['solid/wheelchair','Wheelchair'],
['solid/wheelchair-move','Wheelchair Move'],
['solid/whiskey-glass','Whiskey Glass'],
['brands/whmcs','Whmcs'],
['solid/wifi','Wifi'],
['brands/wikipedia-w','Wikipedia W'],
['solid/wind','Wind'],
['regular/window-maximize','Window Maximize'],
['solid/window-maximize','Window Maximize'],
['regular/window-minimize','Window Minimize'],
['solid/window-minimize','Window Minimize'],
['regular/window-restore','Window Restore'],
['solid/window-restore','Window Restore'],
['brands/windows','Windows'],
['solid/wine-bottle','Wine Bottle'],
['solid/wine-glass','Wine Glass'],
['solid/wine-glass-empty','Wine Glass Empty'],
['brands/wirsindhandwerk','Wirsindhandwerk'],
['brands/wix','Wix'],
['brands/wizards-of-the-coast','Wizards Of The Coast'],
['brands/wodu','Wodu'],
['brands/wolf-pack-battalion','Wolf Pack Battalion'],
['solid/won-sign','Won Sign'],
['brands/wordpress','Wordpress'],
['brands/wordpress-simple','Wordpress Simple'],
['solid/worm','Worm'],
['brands/wpbeginner','Wpbeginner'],
['brands/wpexplorer','Wpexplorer'],
['brands/wpforms','Wpforms'],
['brands/wpressr','Wpressr'],
['solid/wrench','Wrench'],
['solid/x','X'],
['solid/x-ray','X Ray'],
['brands/x-twitter','X Twitter'],
['brands/xbox','Xbox'],
['brands/xing','Xing'],
['solid/xmark','Xmark'],
['solid/xmarks-lines','Xmarks Lines'],
['brands/xmpp','Xmpp'],
['brands/xrp','Xrp'],
['brands/xrpl','Xrpl'],
['solid/y','Y'],
['brands/y-combinator','Y Combinator'],
['brands/yahoo','Yahoo'],
['brands/yammer','Yammer'],
['brands/yandex','Yandex'],
['brands/yandex-international','Yandex International'],
['brands/yarn','Yarn'],
['brands/yelp','Yelp'],
['solid/yen-sign','Yen Sign'],
['solid/yin-yang','Yin Yang'],
['brands/yoast','Yoast'],
['brands/youtube','Youtube'],
['brands/youtube-shorts','Youtube Shorts'],
['solid/z','Z'],
['brands/zhihu','Zhihu'],
['brands/zoom','Zoom'],
['brands/zulip','Zulip']
];
